
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: okteto/collaborative-voting-app-api
        name: api
        imagePullPolicy: Always
