
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: okteto/collaborative-voting-app-vote
        name: vote
        env:
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth0
                key: client_id
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth0
                key: client_secret
