apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mult
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mult
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: pchico83/go-cnd:0.2
        name: mult
        ports:
        - containerPort: 8080
